## Lesson-14 Numpy  and Sci-Computing 

1. Numpy 的 aixs
2. Numpy 的 数据连接操作
3. Numpy 的 Broadcast
4. Numpy 的 性能加速对比

### aixs

In [22]:
some_array = [1, 2, 3] * 100

In [21]:
other_array = [-1, -2, -3]  * 100

In [5]:
some_array + other_array

[1, 2, 3, -1, -2, -3]

In [23]:
%%timeit

result = []
for s, t in zip(some_array, other_array):
    result.append(s + t)

21.8 µs ± 50.4 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [7]:
result

[0, 0, 0]

In [8]:
import numpy as np

In [24]:
v1 = np.array([1, 2, 3] * 100)

In [25]:
v2 = np.array([-1, -2, -3] * 100)

In [26]:
%%timeit

v1 + v2

535 ns ± 2.43 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


Numpy 非常重要原因：因为numpy通过c语言实现了大量的操作，而且通过memoryview的方式，直接将数字没有进过赋值，就可以运算，导致运算速度非常快！

+ tensorflow 
+ Pytorch 
+ 都是大量参考了numpy

## axis 是什么呢？

In [33]:
m1 = np.array([
 [1, 2], 
 [3, 4],
 [5, 6],
])

m2 = np.array([
 [-1, -2], 
 [-3, -4],
 [-5, -6],
])

In [47]:
np.sum([m1, m2], axis=1)

array([[  9,  12],
       [ -9, -12]])

In [42]:
m4 = np.array([
    m1, m2
])

In [44]:
m4.shape

(2, 3, 2)

In [41]:
m3 = np.array([
    [1, 2, 3],
    [-1, -2, -3]
])

In [40]:
m3.shape

(2, 3)

In [38]:
m1.shape

(3, 2)

In [35]:
np.sum([m1, m2])

0

In [36]:
np.sum([m1, m2], axis=0)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [32]:
np.sum([v1, v2])

0

In [31]:
np.sum([v1, v2], axis=0)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [62]:
np.concatenate([m1, m2], axis=0)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [-1, -2],
       [-3, -4],
       [-5, -6]])

In [51]:
np.concatenate([m1, m2], axis=1)

array([[ 1,  2, -1, -2],
       [ 3,  4, -3, -4],
       [ 5,  6, -5, -6]])

In [103]:
np.stack([m1, m2] * 10, axis=2).shape

(3, 2, 20)

In [99]:
help(np.stack)

Help on function stack in module numpy:

stack(arrays, axis=0, out=None)
    Join a sequence of arrays along a new axis.
    
    The ``axis`` parameter specifies the index of the new axis in the
    dimensions of the result. For example, if ``axis=0`` it will be the first
    dimension and if ``axis=-1`` it will be the last dimension.
    
    .. versionadded:: 1.10.0
    
    Parameters
    ----------
    arrays : sequence of array_like
        Each array must have the same shape.
    
    axis : int, optional
        The axis in the result array along which the input arrays are stacked.
    
    out : ndarray, optional
        If provided, the destination to place the result. The shape must be
        correct, matching that of what stack would have returned if no
        out argument were specified.
    
    Returns
    -------
    stacked : ndarray
        The stacked array has one more dimension than the input arrays.
    
    See Also
    --------
    concatenate : Join a sequenc

In [97]:
m1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [98]:
m2

array([[-1, -2],
       [-3, -4],
       [-5, -6]])

In [96]:
np.stack([m1, m2], axis=1)

array([[[ 1,  2],
        [-1, -2]],

       [[ 3,  4],
        [-3, -4]],

       [[ 5,  6],
        [-5, -6]]])

In [94]:
np.stack([m1, m2], axis=1).shape

(3, 2, 2)

In [73]:
stacked_trainig_data = np.stack([m1, m2] * 10000, axis=0)

In [79]:
stacked_trainig_data.shape

(20000, 3, 2)

In [90]:
indices = np.random.choice(range(len(stacked_trainig_data)), size=100)

In [113]:
stacked_trainig_data[(0, 1, 1)]

4

In [116]:
stacked_trainig_data[np.array([0, 1, 2, 3, 4])]

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[-1, -2],
        [-3, -4],
        [-5, -6]],

       [[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[-1, -2],
        [-3, -4],
        [-5, -6]],

       [[ 1,  2],
        [ 3,  4],
        [ 5,  6]]])

In [91]:
stacked_trainig_data[indices]

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[-1, -2],
        [-3, -4],
        [-5, -6]],

       [[-1, -2],
        [-3, -4],
        [-5, -6]],

       [[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[-1, -2],
        [-3, -4],
        [-5, -6]],

       [[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[-1, -2],
        [-3, -4],
        [-5, -6]],

       [[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[-1, -2],
        [-3, -4],
        [-5, -6]],

       [[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[-1, -2],
        [-3, -4],
        [-5, -6]],

       [[-1, -2],
        [-3, -4],
        [-5, -6]],

       [[-1, -2],
        [-3, -4],
        [-5, -6]],

       [[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[-1, -2],
        [-3, -4],
        [-5, -6]],

       [[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[-1, -2],
        [-3, -4],
        [-5,

In [119]:
np.mean(stacked_trainig_data)

0.0

In [126]:
m1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [125]:
np.mean(m1, axis=0)

array([3., 4.])

In [127]:
np.mean(m1, axis=1)

array([1.5, 3.5, 5.5])

In [120]:
np.mean(stacked_trainig_data, axis=0)

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [121]:
np.mean(stacked_trainig_data, axis=1)

array([[ 3.,  4.],
       [-3., -4.],
       [ 3.,  4.],
       ...,
       [-3., -4.],
       [ 3.,  4.],
       [-3., -4.]])

In [122]:
np.mean(stacked_trainig_data, axis=2)

array([[ 1.5,  3.5,  5.5],
       [-1.5, -3.5, -5.5],
       [ 1.5,  3.5,  5.5],
       ...,
       [-1.5, -3.5, -5.5],
       [ 1.5,  3.5,  5.5],
       [-1.5, -3.5, -5.5]])

### Different. Initialized and Size

In [132]:
m_5 = np.array([0 ,1 ,2 ,3, 4, ])

In [131]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [133]:
np.zeros_like(m_5)

array([0, 0, 0, 0, 0])

In [136]:
np.ones((10, 10))
np.ones_like(m_5)

array([1, 1, 1, 1, 1])

In [138]:
help(np.empty)

Help on built-in function empty in module numpy:

empty(...)
    empty(shape, dtype=float, order='C')
    
    Return a new array of given shape and type, without initializing entries.
    
    Parameters
    ----------
    shape : int or tuple of int
        Shape of the empty array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        Desired output data-type for the array, e.g, `numpy.int8`. Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of uninitialized (arbitrary) data of the given shape, dtype, and
        order.  Object arrays will be initialized to None.
    
    See Also
    --------
    empty_like : Return an empty array with shape and type of input.
    ones : Return a new array setting values to one.
    zeros : Return a new array 

In [137]:
np.empty((10, 3))

array([[0.00000000e+000, 2.47032823e-323, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 5.02034658e+175],
       [1.10547134e+165, 3.24979765e-057, 2.44997269e-056],
       [1.32787036e-075, 1.47763641e+248, 1.16096346e-028],
       [7.69165785e+218, 1.35617292e+248, 3.58801215e+175],
       [3.42044456e-032, 1.65636678e-047, 2.51361175e+180],
       [4.26581191e-096, 6.32299154e+233, 3.65588282e+233],
       [1.74569531e+238, 1.11763132e+261, 1.16318408e-028],
       [2.24729310e+174, 1.56605686e-076, 1.08535842e-071],
       [4.17328100e-057, 2.00375949e-052, 2.66289656e-312]])

In [140]:
help(np.full)

Help on function full in module numpy:

full(shape, fill_value, dtype=None, order='C')
    Return a new array of given shape and type, filled with `fill_value`.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    fill_value : scalar
        Fill value.
    dtype : data-type, optional
        The desired data-type for the array  The default, None, means
         `np.array(fill_value).dtype`.
    order : {'C', 'F'}, optional
        Whether to store multidimensional data in C- or Fortran-contiguous
        (row- or column-wise) order in memory.
    
    Returns
    -------
    out : ndarray
        Array of `fill_value` with the given shape, dtype, and order.
    
    See Also
    --------
    full_like : Return a new array with shape of input filled with value.
    empty : Return a new uninitialized array.
    ones : Return a new array setting values to one.
    zeros : Return a new array setting values to

In [142]:
np.random.uniform(size=(3, 3))

array([[0.82234236, 0.68734333, 0.06556701],
       [0.339369  , 0.19362063, 0.14487851],
       [0.85068164, 0.03225473, 0.37730373]])

In [146]:
random_weights = np.random.normal(size=(10, 3))

In [147]:
random_weights

array([[-1.50485355,  1.04732138, -0.05088461],
       [ 0.99940569, -1.62339551,  0.95004181],
       [ 0.25668254, -1.06416696, -1.61435877],
       [ 0.26323169, -1.27279186, -1.66096579],
       [-1.00376113, -0.6323056 ,  1.53278884],
       [ 1.24122959,  0.36579175,  0.96935839],
       [-0.67612973, -1.58749664, -0.05263275],
       [ 1.73272514, -0.40487562,  0.49411906],
       [-0.14334745, -0.14302463,  0.35964735],
       [ 1.04434921,  0.30880889, -0.19436776]])

In [148]:
random_weights.reshape(5, 6)

array([[-1.50485355,  1.04732138, -0.05088461,  0.99940569, -1.62339551,
         0.95004181],
       [ 0.25668254, -1.06416696, -1.61435877,  0.26323169, -1.27279186,
        -1.66096579],
       [-1.00376113, -0.6323056 ,  1.53278884,  1.24122959,  0.36579175,
         0.96935839],
       [-0.67612973, -1.58749664, -0.05263275,  1.73272514, -0.40487562,
         0.49411906],
       [-0.14334745, -0.14302463,  0.35964735,  1.04434921,  0.30880889,
        -0.19436776]])

In [149]:
random_weights.reshape(-1)

array([-1.50485355,  1.04732138, -0.05088461,  0.99940569, -1.62339551,
        0.95004181,  0.25668254, -1.06416696, -1.61435877,  0.26323169,
       -1.27279186, -1.66096579, -1.00376113, -0.6323056 ,  1.53278884,
        1.24122959,  0.36579175,  0.96935839, -0.67612973, -1.58749664,
       -0.05263275,  1.73272514, -0.40487562,  0.49411906, -0.14334745,
       -0.14302463,  0.35964735,  1.04434921,  0.30880889, -0.19436776])

In [150]:
random_weights.reshape(-1, 6)

array([[-1.50485355,  1.04732138, -0.05088461,  0.99940569, -1.62339551,
         0.95004181],
       [ 0.25668254, -1.06416696, -1.61435877,  0.26323169, -1.27279186,
        -1.66096579],
       [-1.00376113, -0.6323056 ,  1.53278884,  1.24122959,  0.36579175,
         0.96935839],
       [-0.67612973, -1.58749664, -0.05263275,  1.73272514, -0.40487562,
         0.49411906],
       [-0.14334745, -0.14302463,  0.35964735,  1.04434921,  0.30880889,
        -0.19436776]])

In [163]:
random_weights.reshape(-1, 6).T

array([[-1.50485355,  0.25668254, -1.00376113, -0.67612973, -0.14334745],
       [ 1.04732138, -1.06416696, -0.6323056 , -1.58749664, -0.14302463],
       [-0.05088461, -1.61435877,  1.53278884, -0.05263275,  0.35964735],
       [ 0.99940569,  0.26323169,  1.24122959,  1.73272514,  1.04434921],
       [-1.62339551, -1.27279186,  0.36579175, -0.40487562,  0.30880889],
       [ 0.95004181, -1.66096579,  0.96935839,  0.49411906, -0.19436776]])

In [164]:
random_weights.reshape(-1, 1, 6)

array([[[-1.50485355,  1.04732138, -0.05088461,  0.99940569,
         -1.62339551,  0.95004181]],

       [[ 0.25668254, -1.06416696, -1.61435877,  0.26323169,
         -1.27279186, -1.66096579]],

       [[-1.00376113, -0.6323056 ,  1.53278884,  1.24122959,
          0.36579175,  0.96935839]],

       [[-0.67612973, -1.58749664, -0.05263275,  1.73272514,
         -0.40487562,  0.49411906]],

       [[-0.14334745, -0.14302463,  0.35964735,  1.04434921,
          0.30880889, -0.19436776]]])

In [145]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [167]:
m = np.genfromtxt('numbers.dat', delimiter=',')

In [174]:
np.savetxt('new_data.dat', m)

In [175]:
!ls

lesson-14.ipynb new_data.dat    numbers.dat


In [176]:
!less new_data.dat

5.819602537672219356e-01 5.087776563724527579e-01 2.784142127232769326e-03 5.957311390647657134e-01 8.689860709925093518e-01
9.264195805336176148e-01 7.800147882622944229e-01 9.676056206751270095e-01 2.205256712547208897e-01 2.061922083494628355e-01
6.783337181089943435e-01 5.869145106077806595e-01 2.952358654499552815e-01 3.801997771883158794e-01 6.889636599796673533e-01
4.292230072013289988e-01 4.257627535426546928e-01 7.021841592214385086e-01 8.686417248472499963e-02 3.583006283237899492e-02
5.263115697205873467e-01 8.799444420949060763e-01 1.194754090830576487e-01 7.479153109619839368e-01 9.440646400270436001e-02
1.232809121329454527e-01 5.186331522192256793e-01 9.809687646542244455e-01 8.783019711016459841e-02 3.133205853162499555e-01
7.516376862486182642e-01 8.785274617838342293e-01 8.784804332149217521e-01 8.749962343094666029e-01 4.158675577860713179e-01
1.320108327988774866e-01 5.535512918624858614e-01 7.234839929208859433e-01 8.580655831714277815e-01 2.624920180979781748e-01


## Data Access

In [181]:
m.shape

(8, 5)

In [183]:
m

array([[0.58196025, 0.50877766, 0.00278414, 0.59573114, 0.86898607],
       [0.92641958, 0.78001479, 0.96760562, 0.22052567, 0.20619221],
       [0.67833372, 0.58691451, 0.29523587, 0.38019978, 0.68896366],
       [0.42922301, 0.42576275, 0.70218416, 0.08686417, 0.03583006],
       [0.52631157, 0.87994444, 0.11947541, 0.74791531, 0.09440646],
       [0.12328091, 0.51863315, 0.98096876, 0.0878302 , 0.31332059],
       [0.75163769, 0.87852746, 0.87848043, 0.87499623, 0.41586756],
       [0.13201083, 0.55355129, 0.72348399, 0.85806558, 0.26249202]])

### 直接索引   

In [184]:
m[1, 2]

0.967605620675127

In [185]:
m[(1, 2)]

0.967605620675127

In [186]:
import random

In [227]:
def generate_coord():
    return random.randint(0, 7), random.randint(0, 4)

In [242]:
m[generate_coord()]

0.967605620675127

### slice切片

In [261]:
m

array([[0.58196025, 0.50877766, 0.00278414, 0.59573114, 0.86898607],
       [0.92641958, 0.78001479, 0.96760562, 0.22052567, 0.20619221],
       [0.67833372, 0.58691451, 0.29523587, 0.38019978, 0.68896366],
       [0.42922301, 0.42576275, 0.70218416, 0.08686417, 0.03583006],
       [0.52631157, 0.87994444, 0.11947541, 0.74791531, 0.09440646],
       [0.12328091, 0.51863315, 0.98096876, 0.0878302 , 0.31332059],
       [0.75163769, 0.87852746, 0.87848043, 0.87499623, 0.41586756],
       [0.13201083, 0.55355129, 0.72348399, 0.85806558, 0.26249202]])

In [270]:
m[:, 0:2]

array([[0.58196025, 0.50877766],
       [0.92641958, 0.78001479],
       [0.67833372, 0.58691451],
       [0.42922301, 0.42576275],
       [0.52631157, 0.87994444],
       [0.12328091, 0.51863315],
       [0.75163769, 0.87852746],
       [0.13201083, 0.55355129]])

In [245]:
m[2]

array([0.67833372, 0.58691451, 0.29523587, 0.38019978, 0.68896366])

In [274]:
%%timeit 

array = []
for row in m:
    array.append(row[2])
array = np.array(array)

3.92 µs ± 13.9 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [273]:
%%timeit 

sub_m = m[:, 2]

191 ns ± 0.483 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [275]:
m

array([[0.58196025, 0.50877766, 0.00278414, 0.59573114, 0.86898607],
       [0.92641958, 0.78001479, 0.96760562, 0.22052567, 0.20619221],
       [0.67833372, 0.58691451, 0.29523587, 0.38019978, 0.68896366],
       [0.42922301, 0.42576275, 0.70218416, 0.08686417, 0.03583006],
       [0.52631157, 0.87994444, 0.11947541, 0.74791531, 0.09440646],
       [0.12328091, 0.51863315, 0.98096876, 0.0878302 , 0.31332059],
       [0.75163769, 0.87852746, 0.87848043, 0.87499623, 0.41586756],
       [0.13201083, 0.55355129, 0.72348399, 0.85806558, 0.26249202]])

## 为什么切片，numpy的索引这么快呢？ 

使用了python的memoryview机制

In [280]:
sub_m = m[0:2, 3: 6]

In [283]:
sub_m[1, 1] = -0.2

In [284]:
m

array([[ 0.58196025,  0.50877766,  0.00278414,  0.59573114,  0.86898607],
       [ 0.92641958,  0.78001479,  0.96760562,  0.22052567, -0.2       ],
       [ 0.67833372,  0.58691451,  0.29523587,  0.38019978,  0.68896366],
       [ 0.42922301,  0.42576275,  0.70218416,  0.08686417,  0.03583006],
       [ 0.52631157,  0.87994444,  0.11947541,  0.74791531,  0.09440646],
       [ 0.12328091,  0.51863315,  0.98096876,  0.0878302 ,  0.31332059],
       [ 0.75163769,  0.87852746,  0.87848043,  0.87499623,  0.41586756],
       [ 0.13201083,  0.55355129,  0.72348399,  0.85806558,  0.26249202]])

In [287]:
m[[1, 3], [0, 2]]

array([0.92641958, 0.70218416])

## boolean / 条件索引

In [293]:
m.reshape(-1)

array([ 0.58196025,  0.50877766,  0.00278414,  0.59573114,  0.86898607,
        0.92641958,  0.78001479,  0.96760562,  0.22052567, -0.2       ,
        0.67833372,  0.58691451,  0.29523587,  0.38019978,  0.68896366,
        0.42922301,  0.42576275,  0.70218416,  0.08686417,  0.03583006,
        0.52631157,  0.87994444,  0.11947541,  0.74791531,  0.09440646,
        0.12328091,  0.51863315,  0.98096876,  0.0878302 ,  0.31332059,
        0.75163769,  0.87852746,  0.87848043,  0.87499623,  0.41586756,
        0.13201083,  0.55355129,  0.72348399,  0.85806558,  0.26249202])